<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fdl</string>
	</array>
	<key>name</key>
	<string>Gezel</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$option)\s+("\w+")</string>
			<key>name</key>
			<string>meta.gezel.option</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(ipblock)\s+([a-zA-Z]\w*)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.gezel.ipblock.start</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inputoutput</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(dp)\s+([a-zA-Z]\w*)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.gezel.dp.start</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inputoutput</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(dp)\s+([a-zA-Z]\w*)\s*{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.gezel.dp.headless</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dpBody</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(fsm)\s+([a-zA-Z]\w*)\s*\(([a-zA-Z]\w*)\)\s*{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.gezel.fsm</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#fsmBody</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>{</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.gezel.dp.body</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#dpBody</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(system)\s+([a-zA-Z]\w*)\s*{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.gezel.system</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\/\/.+</string>
					<key>name</key>
					<string>comment.line.double-slash</string>
				</dict>
			</array>
		</dict>
		<key>display</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\$display)\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\);</string>
					<key>name</key>
					<string>meta.gezel.display</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>dpBody</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#trace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(always)\s*{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>meta.gezel.always</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#scriptBody</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(reg)\s+([a-zA-Z]\w*)\s+:\s*(ns|tc)\((\d*)\);</string>
					<key>name</key>
					<string>meta.gezel.reg</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(sfg)\s+([a-zA-Z]\w*)\s*{</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>meta.gezel.sfg</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#scriptBody</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(sig)\s+([a-zA-Z]\w*)\s*:\s*(ns|tc)\((\d*)\);</string>
					<key>name</key>
					<string>meta.gezel.signal</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(use)\s+([a-zA-Z]\w*)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\);</string>
					<key>name</key>
					<string>meta.gezel.function.call</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[a-zA-Z]\w*</string>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(iptype)\s+("\w+");</string>
					<key>name</key>
					<string>meta.gezel.iptype</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(ipparm)\s+("[\w\\:=\./]+");</string>
					<key>name</key>
					<string>meta.gezel.ipparam</string>
				</dict>
			</array>
		</dict>
		<key>fsmBody</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#initial</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#state</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#stateCmd</string>
				</dict>
			</array>
		</dict>
		<key>function</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([a-zA-Z]\w*)\s*\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\);</string>
					<key>name</key>
					<string>meta.gezel.function</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[a-zA-Z]\w*</string>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>initial</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(initial)\s+([a-zA-Z]\w*)\s*;</string>
					<key>name</key>
					<string>meta.gezel.initial</string>
				</dict>
			</array>
		</dict>
		<key>inputoutput</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\s*(in|out)\s+([a-zA-Z]\w*)\s*:\s*(ns|tc)\((\d*)\);?</string>
					<key>name</key>
					<string>meta.gezel.inputoutput</string>
				</dict>
			</array>
		</dict>
		<key>number</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric</string>
						</dict>
					</dict>
					<key>match</key>
					<string>[^a-zA-Z_](0x|0b)*(-*\d+)</string>
					<key>name</key>
					<string>meta.gezel.number</string>
				</dict>
			</array>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[(?:&gt;&gt;)(?:&lt;&lt;)\*=&amp;\?\+-]</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</array>
		</dict>
		<key>scriptBody</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#display</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
			</array>
		</dict>
		<key>selector</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\?)[\s\w]*\w[\s\w]*(:)</string>
					<key>name</key>
					<string>meta.gezel.selector</string>
				</dict>
			</array>
		</dict>
		<key>state</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(state)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>name</key>
					<string>meta.gezel.state</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>[a-zA-Z]\w*</string>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>stateCmd</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(@)[a-zA-Z]\w*\s*\([a-zA-Z]\w*\)\s*(-&gt;)\s*[a-zA-Z]\w*;</string>
					<key>name</key>
					<string>meta.gezel.stateCmd</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>"[^"]*"</string>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
			</array>
		</dict>
		<key>trace</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$trace)\((\w+),\s("[\w/\.:]+")\);</string>
					<key>name</key>
					<string>meta.gezel.trace</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gezel</string>
	<key>uuid</key>
	<string>59bc7a9a-8dff-4bfa-bbc5-f6ca5161344b</string>
</dict>
</plist>
